// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuyWUX2GLCQFbraN2UaR4HIDxNmEiKtGc',
    appId: '1:704694147154:web:fb7222b73c4368fceb278b',
    messagingSenderId: '704694147154',
    projectId: 'pillsend-d22b9',
    authDomain: 'pillsend-d22b9.firebaseapp.com',
    storageBucket: 'pillsend-d22b9.appspot.com',
    measurementId: 'G-JCZ5066W0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdEqeSddOmdwb4TSQGqZ2eY2FUhZUaT7E',
    appId: '1:704694147154:android:5bd74c8b22bca6fceb278b',
    messagingSenderId: '704694147154',
    projectId: 'pillsend-d22b9',
    storageBucket: 'pillsend-d22b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpZun-9aDL17c0fTFTKoQWDO_iSDXBHg',
    appId: '1:704694147154:ios:a390d343a7f07ea2eb278b',
    messagingSenderId: '704694147154',
    projectId: 'pillsend-d22b9',
    storageBucket: 'pillsend-d22b9.appspot.com',
    androidClientId:
        '704694147154-sor906pn3crfcnmrhrio8s5me4mlnvp1.apps.googleusercontent.com',
    iosClientId:
        '704694147154-52b785cu9t8k7f0g66v115hnq87mhlf0.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.pillsend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpZun-9aDL17c0fTFTKoQWDO_iSDXBHg',
    appId: '1:704694147154:ios:77d770064830541feb278b',
    messagingSenderId: '704694147154',
    projectId: 'pillsend-d22b9',
    storageBucket: 'pillsend-d22b9.appspot.com',
    androidClientId:
        '704694147154-sor906pn3crfcnmrhrio8s5me4mlnvp1.apps.googleusercontent.com',
    iosClientId:
        '704694147154-g99cbnfnn5vo95gh0vonbbsbh0uqn5m6.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.pillsend.RunnerTests',
  );
}
